### ISSUE TITLE
Get Selected Item From Combo Box --> FAIL: Wait popup expanded

### ISSUE THREAD

**Issue by justingamble** [robotframework/SwingLibrary#46] opened 2013-08-16 00:10 UTC
# Software versions:

Robot Framework 2.8.1 (Jython 2.5.3 on java1.6.0_45)
SwingLibray 1.6.0

Operating System: 64-bit Linux (with Mint v14)
$ uname -a
Linux adelais 3.5.0-17-generic #28-Ubuntu SMP Tue Oct 9 19:31:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
# Issue

My program tests 78 station segments.  For each segment Robot Framework launches the application, and verifies that "Get Selected Item From Combo Box" returns what is expected to be there:  

```
| *Setting*   | *Value*         |
| Library     | SwingLibrary    |
| Library     | OperatingSystem |

| Suite Setup    | Start CSM Application |
| Suite Teardown | Stop CSM Application  |

| *Test Case*    | *Action*                   | *Argument*       |
| Verify Dialog  | Select Dialog              | AddRecordDialog |
|                | ${lineno}=                 | Get Selected Item From Combo Box |    LineComboBox |
|                | ${upstream}=               | Get Selected Item From Combo Box | UpstreamLocationComboBox |
|                | ${downstream}=             | Get Selected Item From Combo Box | DownstreamLocationComboBox |
|                | Should Be Equal As Strings | ${lineno}       | 2 |
|                | Should Be Equal As Strings | ${upstream}     | EP |
|                | Should Be Equal As Strings | ${downstream}   | KG |

| *Keyword* |
| Start CSM Application | Start Application In Separate Thread | com.csmt.AppLauncher | -LINE=2 | -STATION=KG |

| Stop CSM Application  | ${pid}=  | Run         | ps -A -o pid,cmd|grep CSM|head -n 1|cut -f 1 -d" " |
|                       | Run      | kill ${pid} |
```

On occasion (i.e. when it happens, it affects 5/78 stations), I'll see the "Get Selected Item From Combo Box" keyword fail with this message:  "Wait popup expanded".  Repeating the same test again, immediately after the failure, will pass.
# Stacktrace (extracted from debug.txt)

+-- START KW: ${upstream} = SwingLibrary.Get Selected Item From Combo Box [ UpstreamLocationComboBox ]
Wait popup expanded
java.lang.RuntimeException: 
    at org.robotframework.javalib.library.AnnotationLibrary.retrieveInnerException(AnnotationLibrary.java:101)
    at org.robotframework.javalib.library.AnnotationLibrary.runKeyword(AnnotationLibrary.java:83)
    at org.robotframework.swing.SwingLibrary.runKeyword(SwingLibrary.java:105)
    at robot.model.testcase$py.visit$7(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/testcase.py:65)
    at robot.model.testcase$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/testcase.py)
    at robot.model.itemlist$py.visit$9(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/itemlist.py:54)
    at robot.model.itemlist$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/itemlist.py)
    at robot.model.visitor$py.visit_suite$2(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/visitor.py:22)
    at robot.model.visitor$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/visitor.py)
    at robot.model.testsuite$py.visit$19(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/testsuite.py:152)
    at robot.model.testsuite$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/model/testsuite.py)
    at robot.run$py.main$3(/opt/jython/jython2.5.3/Lib/site-packages/robot/run.py:391)
    at robot.run$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/run.py)
    at robot.utils.application$py._execute$10(/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/application.py:88)
    at robot.utils.application$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/application.py)
    at robot.utils.application$py.execute_cli$5(/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/application.py:45)
    at robot.utils.application$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/utils/application.py)
    at robot.run$py.run_cli$7(/opt/jython/jython2.5.3/Lib/site-packages/robot/run.py:415)
    at robot.run$py.call_function(/opt/jython/jython2.5.3/Lib/site-packages/robot/run.py)
Caused by: org.robotframework.org.netbeans.jemmy.TimeoutExpiredException: Wait popup expanded
    at org.robotframework.org.netbeans.jemmy.Waiter.waitAction(Waiter.java:147)
    at org.robotframework.org.netbeans.jemmy.operators.JComboBoxOperator.waitList(JComboBoxOperator.java:418)
    at org.robotframework.swing.combobox.ItemTextExtractor.getRenderedComponent(ItemTextExtractor.java:61)
    at org.robotframework.swing.combobox.ItemTextExtractor.getComponentWithText(ItemTextExtractor.java:54)
    at org.robotframework.swing.combobox.ItemTextExtractor.getTextFromRenderedComponent(ItemTextExtractor.java:44)
    at org.robotframework.swing.combobox.ComboBoxOperator$2.executeWhenComboBoxOpen(ComboBoxOperator.java:104)
    at org.robotframework.swing.combobox.ComboBoxOperator$ComboboxAction.execute(ComboBoxOperator.java:141)
    at org.robotframework.swing.combobox.ComboBoxOperator.getSelectedItem(ComboBoxOperator.java:101)
    at org.robotframework.swing.keyword.combobox.ComboBoxKeywords.getSelectedItemFromComboBox(ComboBoxKeywords.java:74)
    at org.robotframework.javalib.reflection.KeywordInvoker.invoke(KeywordInvoker.java:50)
    at org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$1.execute(AnnotationKeywordExtractor.java:62)
    at org.robotframework.javalib.library.KeywordFactoryBasedLibrary.runKeyword(KeywordFactoryBasedLibrary.java:37)
    at org.robotframework.javalib.library.AnnotationLibrary.runKeyword(AnnotationLibrary.java:81)
    ... 137 more
+-- END KW: ${upstream} = SwingLibrary.Get Selected Item From Combo Box (10275)

**Comment by WojtekKowaluk** [comment] 2015-06-10 08:52
Seems this is solved already with https://github.com/robotframework/SwingLibrary/pull/66 .

**Comment by filipecduarte** [comment] 2016-09-09 09:28
I have this issue, too. 
In my case the combobox is disabled and in this case, the combobox don't expanded, but have one value select. 
What is the way to get this value? Get Selected Item From Combo Box don't work. :(

**Comment by BeniGroza** [comment] 2019-02-15 08:42
Hi 
I was trying to reproduce this issue when combobox is disabled but it works for me with Get Selected Item From Combo Box. Can you give me more details about your test, errors and environment?
Br

**Comment by mihaiparvu** [comment] 2019-03-27 08:32
Closing until new info available.

**Closed by mihaiparvu** 2019-03-27 08:32 UTC
