### ISSUE TITLE
"Tree Node Should Be Leaf" gives wrong results

### ISSUE THREAD

**Issue by tarand** [robotframework/SwingLibrary#78] opened 2015-10-26 11:55 UTC
I encounter heavy problems with that keyword. I call it upon a node which definitely is a leaf - I can see that also from the Screenshot that is captured in the TearDown of the failing test case. But the keyword fails saying "Tree node 'Groups|PEMTestGroup|Roles' is not leaf."

What also astonishes me is that the Keyword returns extremely fast (around 0.010 sec). 

I also tried with "wait until keyword succeeds" around the call, but with the same results.

I'm using RemoteSwingLibrary 2.0.3 (which includes SwingLibrary 1.9.4 as the doc says).

KEYWORD: RemoteSwingLibrary.Expand Tree Node ${treeIdentifier}, ${expandTreePath}
00:00:00.733 KEYWORD: Pem_GUI_Keywords.Select And Refresh Groups Tree
00:00:00.047 KEYWORD: Pem_GUI_Keywords.Run Tree Related Keyword RemoteSwingLibrary.Tree Node Should Be Leaf, ${treeIdentifier}, ${expandTreePath}|${expectedItem}
Documentation:  

Expands the expandTreePath and checks that the expectedTreePath is a leaf node. This keyword should be used within WaitUntilKeywordSucceeds.
Start / End / Elapsed:  20151026 12:23:47.721 / 20151026 12:23:47.768 / 00:00:00.047
00:00:00.004 KEYWORD: ${oldTimeout1} = RemoteSwingLibrary.Set Jemmy Timeout JTreeOperator.WaitNodeExpandedTimeout, 3
00:00:00.008 KEYWORD: ${oldTimeout2} = RemoteSwingLibrary.Set Jemmy Timeout JTreeOperator.WaitNextNodeTimeout, 3
00:00:00.004 KEYWORD: ${oldTimeout3} = RemoteSwingLibrary.Set Jemmy Timeout JTreeOperator.WaitNodeVisibleTimeout, 3
00:00:00.010 KEYWORD: ${status}, ${result} = BuiltIn.Run Keyword And Ignore Error ${keyword}, @{arguments}
Documentation:  

Runs the given keyword with the given arguments and ignores possible error.
Start / End / Elapsed:  20151026 12:23:47.744 / 20151026 12:23:47.754 / 00:00:00.010
00:00:00.007 KEYWORD: RemoteSwingLibrary.Tree Node Should Be Leaf @{arguments}
Documentation:  

Fails if the node has child nodes.
Start / End / Elapsed:  20151026 12:23:47.744 / 20151026 12:23:47.751 / 00:00:00.007
12:23:47.745    TRACE   Arguments: [ u'GroupExplorerTree' | u'Groups|PEMTestGroup|Roles' ]  
12:23:47.745    DEBUG   Test timeout 15 minutes active. 873.989 seconds left.  
12:23:47.750    FAIL    Tree node 'Groups|PEMTestGroup|Roles' is not leaf.

**Comment by tarand** [comment] 2015-10-27 12:48
I found an explanation for my problem: The node in question is indeed empty, but it is prepared to contain elements (It is a directory node). Obviously such a node is considered to be not a leaf.
I solved my problem with the help of the Get Tree Node Child names keyword. I'm checking if the result list is empty, that does the trick.

**Comment by stasiek** [comment] 2015-10-27 13:53
Good to hear You got Your problem solved.
So is there anything to do here, or can I close the Issue? : )

**Comment by tarand** [comment] 2015-10-27 18:40
For me it’s fine. If you share my opinion about the probable cause (and find the implementation correct), then you can close it.

If you – however – should find that in this particular case the Tree Node Should Be LEAF should succeed, you might need to correct it. (However, that might break existing test cases).

Maybe a note would in the documentation could also help?

**Comment by cristii006** [comment] 2019-01-31 08:16
Hi @tarand, unfortunately the problem you described in the issue is the way SwingLibrary is expected to behave. I.e.  in Java if a tree node is empty it is not considered to be a leaf. This behavior is the also same for SwingLibrary. You mentioned something about ‘preparing your node to contain elements’, but since it  doesn’t ‘contain elements’ the keyword should return the same result. Maybe you could provide an example since I was not able to reproduce the ‘preparation’ part.
BR,
Cristi

**Comment by mihaiparvu** [comment] 2019-03-27 08:23
Closing due to no response. Can be opened later if needed.

**Closed by mihaiparvu** 2019-03-27 08:23 UTC
